// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Gateway is an autogenerated mock type for the Gateway type
type Gateway struct {
	mock.Mock
}

// Deposit provides a mock function with given fields: ctx, amount
func (_m *Gateway) Deposit(ctx context.Context, amount float64) (common.Hash, *big.Int, error) {
	ret := _m.Called(ctx, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 common.Hash
	var r1 *big.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, float64) (common.Hash, *big.Int, error)); ok {
		return rf(ctx, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64) common.Hash); ok {
		r0 = rf(ctx, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64) *big.Int); ok {
		r1 = rf(ctx, amount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*big.Int)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, float64) error); ok {
		r2 = rf(ctx, amount)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// EmergencyWithdraw provides a mock function with given fields: ctx
func (_m *Gateway) EmergencyWithdraw(ctx context.Context) (common.Hash, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EmergencyWithdraw")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (common.Hash, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) common.Hash); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FromAddress provides a mock function with no fields
func (_m *Gateway) FromAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FromAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, addr
func (_m *Gateway) GetBalance(ctx context.Context, addr common.Address) (*big.Int, error) {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) (*big.Int, error)); ok {
		return rf(ctx, addr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) *big.Int); ok {
		r0 = rf(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = rf(ctx, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContractBalance provides a mock function with given fields: ctx
func (_m *Gateway) GetContractBalance(ctx context.Context) (*big.Int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetContractBalance")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, amount
func (_m *Gateway) Withdraw(ctx context.Context, amount float64) (common.Hash, *big.Int, error) {
	ret := _m.Called(ctx, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 common.Hash
	var r1 *big.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, float64) (common.Hash, *big.Int, error)); ok {
		return rf(ctx, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64) common.Hash); ok {
		r0 = rf(ctx, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64) *big.Int); ok {
		r1 = rf(ctx, amount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*big.Int)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, float64) error); ok {
		r2 = rf(ctx, amount)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewGateway creates a new instance of Gateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *Gateway {
	mock := &Gateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
