// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hela-bank-sc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, address, action, amount, txHash, status
func (_m *Repository) Create(ctx context.Context, address string, action string, amount string, txHash string, status string) (*domain.History, error) {
	ret := _m.Called(ctx, address, action, amount, txHash, status)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.History
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*domain.History, error)); ok {
		return rf(ctx, address, action, amount, txHash, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *domain.History); ok {
		r0 = rf(ctx, address, action, amount, txHash, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.History)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, address, action, amount, txHash, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByAddress provides a mock function with given fields: ctx, address
func (_m *Repository) ListByAddress(ctx context.Context, address string) ([]*domain.History, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for ListByAddress")
	}

	var r0 []*domain.History
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.History, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.History); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.History)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
