// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TransactionHistory is an object representing the database table.
type TransactionHistory struct {
	ID        int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Address   string        `boil:"address" json:"address" toml:"address" yaml:"address"`
	Action    string        `boil:"action" json:"action" toml:"action" yaml:"action"`
	Amount    types.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	TXHash    string        `boil:"tx_hash" json:"tx_hash" toml:"tx_hash" yaml:"tx_hash"`
	Status    string        `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *transactionHistoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L transactionHistoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TransactionHistoryColumns = struct {
	ID        string
	Address   string
	Action    string
	Amount    string
	TXHash    string
	Status    string
	CreatedAt string
}{
	ID:        "id",
	Address:   "address",
	Action:    "action",
	Amount:    "amount",
	TXHash:    "tx_hash",
	Status:    "status",
	CreatedAt: "created_at",
}

var TransactionHistoryTableColumns = struct {
	ID        string
	Address   string
	Action    string
	Amount    string
	TXHash    string
	Status    string
	CreatedAt string
}{
	ID:        "transaction_histories.id",
	Address:   "transaction_histories.address",
	Action:    "transaction_histories.action",
	Amount:    "transaction_histories.amount",
	TXHash:    "transaction_histories.tx_hash",
	Status:    "transaction_histories.status",
	CreatedAt: "transaction_histories.created_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_Decimal struct{ field string }

func (w whereHelpertypes_Decimal) EQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_Decimal) NEQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_Decimal) LT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Decimal) LTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Decimal) GT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Decimal) GTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var TransactionHistoryWhere = struct {
	ID        whereHelperint64
	Address   whereHelperstring
	Action    whereHelperstring
	Amount    whereHelpertypes_Decimal
	TXHash    whereHelperstring
	Status    whereHelperstring
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"transaction_histories\".\"id\""},
	Address:   whereHelperstring{field: "\"transaction_histories\".\"address\""},
	Action:    whereHelperstring{field: "\"transaction_histories\".\"action\""},
	Amount:    whereHelpertypes_Decimal{field: "\"transaction_histories\".\"amount\""},
	TXHash:    whereHelperstring{field: "\"transaction_histories\".\"tx_hash\""},
	Status:    whereHelperstring{field: "\"transaction_histories\".\"status\""},
	CreatedAt: whereHelpertime_Time{field: "\"transaction_histories\".\"created_at\""},
}

// TransactionHistoryRels is where relationship names are stored.
var TransactionHistoryRels = struct {
}{}

// transactionHistoryR is where relationships are stored.
type transactionHistoryR struct {
}

// NewStruct creates a new relationship struct
func (*transactionHistoryR) NewStruct() *transactionHistoryR {
	return &transactionHistoryR{}
}

// transactionHistoryL is where Load methods for each relationship are stored.
type transactionHistoryL struct{}

var (
	transactionHistoryAllColumns            = []string{"id", "address", "action", "amount", "tx_hash", "status", "created_at"}
	transactionHistoryColumnsWithoutDefault = []string{"address", "action", "amount", "tx_hash", "status"}
	transactionHistoryColumnsWithDefault    = []string{"id", "created_at"}
	transactionHistoryPrimaryKeyColumns     = []string{"id"}
	transactionHistoryGeneratedColumns      = []string{}
)

type (
	// TransactionHistorySlice is an alias for a slice of pointers to TransactionHistory.
	// This should almost always be used instead of []TransactionHistory.
	TransactionHistorySlice []*TransactionHistory
	// TransactionHistoryHook is the signature for custom TransactionHistory hook methods
	TransactionHistoryHook func(context.Context, boil.ContextExecutor, *TransactionHistory) error

	transactionHistoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	transactionHistoryType                 = reflect.TypeOf(&TransactionHistory{})
	transactionHistoryMapping              = queries.MakeStructMapping(transactionHistoryType)
	transactionHistoryPrimaryKeyMapping, _ = queries.BindMapping(transactionHistoryType, transactionHistoryMapping, transactionHistoryPrimaryKeyColumns)
	transactionHistoryInsertCacheMut       sync.RWMutex
	transactionHistoryInsertCache          = make(map[string]insertCache)
	transactionHistoryUpdateCacheMut       sync.RWMutex
	transactionHistoryUpdateCache          = make(map[string]updateCache)
	transactionHistoryUpsertCacheMut       sync.RWMutex
	transactionHistoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var transactionHistoryAfterSelectMu sync.Mutex
var transactionHistoryAfterSelectHooks []TransactionHistoryHook

var transactionHistoryBeforeInsertMu sync.Mutex
var transactionHistoryBeforeInsertHooks []TransactionHistoryHook
var transactionHistoryAfterInsertMu sync.Mutex
var transactionHistoryAfterInsertHooks []TransactionHistoryHook

var transactionHistoryBeforeUpdateMu sync.Mutex
var transactionHistoryBeforeUpdateHooks []TransactionHistoryHook
var transactionHistoryAfterUpdateMu sync.Mutex
var transactionHistoryAfterUpdateHooks []TransactionHistoryHook

var transactionHistoryBeforeDeleteMu sync.Mutex
var transactionHistoryBeforeDeleteHooks []TransactionHistoryHook
var transactionHistoryAfterDeleteMu sync.Mutex
var transactionHistoryAfterDeleteHooks []TransactionHistoryHook

var transactionHistoryBeforeUpsertMu sync.Mutex
var transactionHistoryBeforeUpsertHooks []TransactionHistoryHook
var transactionHistoryAfterUpsertMu sync.Mutex
var transactionHistoryAfterUpsertHooks []TransactionHistoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TransactionHistory) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TransactionHistory) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TransactionHistory) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TransactionHistory) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TransactionHistory) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TransactionHistory) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TransactionHistory) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TransactionHistory) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TransactionHistory) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range transactionHistoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTransactionHistoryHook registers your hook function for all future operations.
func AddTransactionHistoryHook(hookPoint boil.HookPoint, transactionHistoryHook TransactionHistoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		transactionHistoryAfterSelectMu.Lock()
		transactionHistoryAfterSelectHooks = append(transactionHistoryAfterSelectHooks, transactionHistoryHook)
		transactionHistoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		transactionHistoryBeforeInsertMu.Lock()
		transactionHistoryBeforeInsertHooks = append(transactionHistoryBeforeInsertHooks, transactionHistoryHook)
		transactionHistoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		transactionHistoryAfterInsertMu.Lock()
		transactionHistoryAfterInsertHooks = append(transactionHistoryAfterInsertHooks, transactionHistoryHook)
		transactionHistoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		transactionHistoryBeforeUpdateMu.Lock()
		transactionHistoryBeforeUpdateHooks = append(transactionHistoryBeforeUpdateHooks, transactionHistoryHook)
		transactionHistoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		transactionHistoryAfterUpdateMu.Lock()
		transactionHistoryAfterUpdateHooks = append(transactionHistoryAfterUpdateHooks, transactionHistoryHook)
		transactionHistoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		transactionHistoryBeforeDeleteMu.Lock()
		transactionHistoryBeforeDeleteHooks = append(transactionHistoryBeforeDeleteHooks, transactionHistoryHook)
		transactionHistoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		transactionHistoryAfterDeleteMu.Lock()
		transactionHistoryAfterDeleteHooks = append(transactionHistoryAfterDeleteHooks, transactionHistoryHook)
		transactionHistoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		transactionHistoryBeforeUpsertMu.Lock()
		transactionHistoryBeforeUpsertHooks = append(transactionHistoryBeforeUpsertHooks, transactionHistoryHook)
		transactionHistoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		transactionHistoryAfterUpsertMu.Lock()
		transactionHistoryAfterUpsertHooks = append(transactionHistoryAfterUpsertHooks, transactionHistoryHook)
		transactionHistoryAfterUpsertMu.Unlock()
	}
}

// OneG returns a single transactionHistory record from the query using the global executor.
func (q transactionHistoryQuery) OneG(ctx context.Context) (*TransactionHistory, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single transactionHistory record from the query.
func (q transactionHistoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TransactionHistory, error) {
	o := &TransactionHistory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for transaction_histories")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all TransactionHistory records from the query using the global executor.
func (q transactionHistoryQuery) AllG(ctx context.Context) (TransactionHistorySlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all TransactionHistory records from the query.
func (q transactionHistoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (TransactionHistorySlice, error) {
	var o []*TransactionHistory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TransactionHistory slice")
	}

	if len(transactionHistoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all TransactionHistory records in the query using the global executor
func (q transactionHistoryQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all TransactionHistory records in the query.
func (q transactionHistoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count transaction_histories rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q transactionHistoryQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q transactionHistoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if transaction_histories exists")
	}

	return count > 0, nil
}

// TransactionHistories retrieves all the records using an executor.
func TransactionHistories(mods ...qm.QueryMod) transactionHistoryQuery {
	mods = append(mods, qm.From("\"transaction_histories\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"transaction_histories\".*"})
	}

	return transactionHistoryQuery{q}
}

// FindTransactionHistoryG retrieves a single record by ID.
func FindTransactionHistoryG(ctx context.Context, iD int64, selectCols ...string) (*TransactionHistory, error) {
	return FindTransactionHistory(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindTransactionHistory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTransactionHistory(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*TransactionHistory, error) {
	transactionHistoryObj := &TransactionHistory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"transaction_histories\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, transactionHistoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from transaction_histories")
	}

	if err = transactionHistoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return transactionHistoryObj, err
	}

	return transactionHistoryObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *TransactionHistory) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TransactionHistory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no transaction_histories provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(transactionHistoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	transactionHistoryInsertCacheMut.RLock()
	cache, cached := transactionHistoryInsertCache[key]
	transactionHistoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			transactionHistoryAllColumns,
			transactionHistoryColumnsWithDefault,
			transactionHistoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(transactionHistoryType, transactionHistoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(transactionHistoryType, transactionHistoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"transaction_histories\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"transaction_histories\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into transaction_histories")
	}

	if !cached {
		transactionHistoryInsertCacheMut.Lock()
		transactionHistoryInsertCache[key] = cache
		transactionHistoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single TransactionHistory record using the global executor.
// See Update for more documentation.
func (o *TransactionHistory) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the TransactionHistory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TransactionHistory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	transactionHistoryUpdateCacheMut.RLock()
	cache, cached := transactionHistoryUpdateCache[key]
	transactionHistoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			transactionHistoryAllColumns,
			transactionHistoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update transaction_histories, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"transaction_histories\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, transactionHistoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(transactionHistoryType, transactionHistoryMapping, append(wl, transactionHistoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update transaction_histories row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for transaction_histories")
	}

	if !cached {
		transactionHistoryUpdateCacheMut.Lock()
		transactionHistoryUpdateCache[key] = cache
		transactionHistoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q transactionHistoryQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q transactionHistoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for transaction_histories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for transaction_histories")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TransactionHistorySlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TransactionHistorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), transactionHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"transaction_histories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, transactionHistoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in transactionHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all transactionHistory")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *TransactionHistory) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TransactionHistory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no transaction_histories provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(transactionHistoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	transactionHistoryUpsertCacheMut.RLock()
	cache, cached := transactionHistoryUpsertCache[key]
	transactionHistoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			transactionHistoryAllColumns,
			transactionHistoryColumnsWithDefault,
			transactionHistoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			transactionHistoryAllColumns,
			transactionHistoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert transaction_histories, could not build update column list")
		}

		ret := strmangle.SetComplement(transactionHistoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(transactionHistoryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert transaction_histories, could not build conflict column list")
			}

			conflict = make([]string, len(transactionHistoryPrimaryKeyColumns))
			copy(conflict, transactionHistoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"transaction_histories\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(transactionHistoryType, transactionHistoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(transactionHistoryType, transactionHistoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert transaction_histories")
	}

	if !cached {
		transactionHistoryUpsertCacheMut.Lock()
		transactionHistoryUpsertCache[key] = cache
		transactionHistoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single TransactionHistory record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *TransactionHistory) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single TransactionHistory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TransactionHistory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TransactionHistory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), transactionHistoryPrimaryKeyMapping)
	sql := "DELETE FROM \"transaction_histories\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from transaction_histories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for transaction_histories")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q transactionHistoryQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q transactionHistoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no transactionHistoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from transaction_histories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for transaction_histories")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o TransactionHistorySlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TransactionHistorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(transactionHistoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), transactionHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"transaction_histories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, transactionHistoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from transactionHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for transaction_histories")
	}

	if len(transactionHistoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *TransactionHistory) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no TransactionHistory provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TransactionHistory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTransactionHistory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TransactionHistorySlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty TransactionHistorySlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TransactionHistorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TransactionHistorySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), transactionHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"transaction_histories\".* FROM \"transaction_histories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, transactionHistoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TransactionHistorySlice")
	}

	*o = slice

	return nil
}

// TransactionHistoryExistsG checks if the TransactionHistory row exists.
func TransactionHistoryExistsG(ctx context.Context, iD int64) (bool, error) {
	return TransactionHistoryExists(ctx, boil.GetContextDB(), iD)
}

// TransactionHistoryExists checks if the TransactionHistory row exists.
func TransactionHistoryExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"transaction_histories\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if transaction_histories exists")
	}

	return exists, nil
}

// Exists checks if the TransactionHistory row exists.
func (o *TransactionHistory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TransactionHistoryExists(ctx, exec, o.ID)
}
